[package]
name = "serde-doc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-serde-doc"
test = false
doctest = false

[dependencies]
syn = { version = "2.0", features = ["full","extra-traits"] }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }